name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - docker-compose.yml
      - .*ignore
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Docker Image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/mysql-backup-creator
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix=
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
